---
all:
  children:
    galera_prod:
      hosts:
        galera-1:
          ansible_host: 192.168.1.51
          galera_node_id: 1
          galera_bootstrap: true
        galera-2:
          ansible_host: 192.168.1.52
          galera_node_id: 2
        galera-3:
          ansible_host: 192.168.1.53
          galera_node_id: 3
    galera_dev:
      hosts:
        galera-dev-1:
          ansible_host: 192.168.1.61
          galera_node_id: 1
          galera_bootstrap: true
        galera-dev-2:
          ansible_host: 192.168.1.62
          galera_node_id: 2
        galera-dev-3:
          ansible_host: 192.168.1.63
          galera_node_id: 3
    loadbalancer:
      hosts:
        lb-1:
          ansible_host: 192.168.1.55
    monitoring:
      hosts:
        grafana-1:
          ansible_host: 192.168.1.54
