---
prometheus_version: "3.2.1"
prometheus_checksum: "sha256:a622e3007c9109a7f470e1433cbd29bf392596715cf7eea8b81b37fa9d26b7be"
prometheus_port: 9090
grafana_port: 3000
mysqld_exporter_port: 9104
prometheus_scrape_interval: 15s

# PMM Server
pmm_enabled: true
pmm_image: "percona/pmm-server:2"
pmm_port: 8443
pmm_data_volume: "pmm-data"
