---
prometheus_version: "3.2.1"
prometheus_checksum: "sha256:https://github.com/prometheus/prometheus/releases/download/v3.2.1/sha256sums.txt"
prometheus_port: 9090
grafana_port: 3000
mysqld_exporter_port: 9104
prometheus_scrape_interval: 15s

# PMM Server
pmm_enabled: true
pmm_image: "percona/pmm-server:2"
pmm_port: 8443
pmm_data_volume: "pmm-data"
